language: python
python:
    - "2.7"
install: pip install -r requirements.txt
before_install: ./before_install.sh
script: py.test tests

# https://code.google.com/p/google-cloud-sdk/issues/detail?id=727
#before_deploy:
#- gcloud config set app/use_gsutil true

deploy:
    provider: gae
    keyfile: ./rdss-api-gae.json
    project: rdss-api
